### ISSUE TITLE
Link Contacts 2 Companies

### ISSUE THREAD

**Issue by sybnex** [rtCamp/rtbiz#70]
Hi, 

I've made a fresh installation of WP 4.4.1 and rtBiz 1.4.
On the "All Contacts" page I just get => Name, Products, User, Teams.

I'm not able to connect a contact to a company on any page. According to the documentation and all the pictures it should work like this, shouldn't it? 

I'm using rtbiz for the first time.

**Comment by PatelUtkarsh** [comment]
We have removed p2p plugin as a depedency which was providing the UI to connect company and contacts,

you can try installing [p2p plugin](https://wordpress.org/plugins/posts-to-posts/).
