### ISSUE TITLE
Welcome notice is getting overlapped with WordPress notice in WP 5.9 version

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/rtbiz#91]
Notice Issue with WP 5.9 version
![image](https://user-images.githubusercontent.com/41000648/152111561-c4cf04d5-2213-43c7-be0f-9dab486a62d9.png)

---

Notice issue with WP 5.8.1 version
![image](https://user-images.githubusercontent.com/41000648/152111661-f9736c66-7842-42e0-8d9b-1a6d4c1ac1bb.png)

---

@image7 please check the plugin in both WP version & fix the overlapping issue. You might need to add a CSS class/wrapper to fix this issue.  

Current stable changes are available in master so create branch from master & against master with your fixes.

**Comment by ank1traj** [comment]
Hi @image7 

This issue has been fixed.
